# Practicando Numpy

## Creando arrays de número aleatorios

In [8]:
import numpy as np

In [4]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
array2 = np.arange(1,100,10)
array2

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [140]:
array3 = np.random.random(5)
print(array3)
print(array3.shape)
print(array3.size)
array3.dtype

[0.07521014 0.70984252 0.68980557 0.8534292  0.48784645]
(5,)
5


dtype('float64')

In [22]:
array4 = np.random.randint(100, 1000, (3, 4)) 
print(array4)
print(array4.shape)
print(array4.size)

[[855 809 947 531]
 [548 950 199 277]
 [855 897 759 247]]
(3, 4)
12


In [26]:
np.random.seed(0) # Ponemos la semilla a 0 (puede ser cualquier número)
array5 = np.random.rand()
array5

0.5488135039273248

## Selección de valores, indexación

In [123]:
array5 = np.random.randint(40, 540, (5, 6)) 
array5

array([[ 65, 321, 503, 312, 216, 118],
       [ 63, 329, 342, 446, 473, 257],
       [330, 257, 539, 442, 127, 147],
       [509, 532, 297, 534, 289, 263],
       [419, 495, 437, 459, 448,  66]])

In [23]:
array5[1:3] #Coge las filas desde 1 al 3

array([[255, 465, 342, 304, 508,  50],
       [125,  79, 360, 244, 377, 113]])

In [24]:
array5[1]

array([255, 465, 342, 304, 508,  50])

In [25]:
array5[1,3] #Coge el dato concreto

304

In [26]:
array5[0:2,5]

array([116,  50])

In [45]:
array5[array5 >300]

array([448, 426, 522, 401, 335, 509, 483, 453, 351, 439, 437, 381, 385,
       348])

In [125]:
array5.sort()
array5

array([[ 65, 118, 216, 312, 321, 503],
       [ 63, 257, 329, 342, 446, 473],
       [127, 147, 257, 330, 442, 539],
       [263, 289, 297, 509, 532, 534],
       [ 66, 419, 437, 448, 459, 495]])

In [124]:
np.sort(array5)

array([[ 65, 118, 216, 312, 321, 503],
       [ 63, 257, 329, 342, 446, 473],
       [127, 147, 257, 330, 442, 539],
       [263, 289, 297, 509, 532, 534],
       [ 66, 419, 437, 448, 459, 495]])

In [69]:
array5.any(axis=0)

array([ True,  True,  True,  True,  True,  True])

In [102]:
array6 = np.random.random(5)
array6.round() == 1

array([False,  True,  True, False,  True])

In [112]:
array7= np.arange(12).reshape(4,3)
array7

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [113]:
_[1, 1] #El guión bajo coje la anterior variable

4

In [118]:
array8 = np.random.randint(40, 540, (4, 5)) 
array9 = np.random.randint(40, 540, (4, 5))

In [122]:
array8

array([[412,  94, 109, 437, 363],
       [176, 385, 508, 479, 530],
       [219, 390, 132, 508, 219],
       [448, 530,  72, 147,  47]])

In [119]:
array9

array([[212, 293,  86, 452, 405],
       [432, 207, 338, 200, 104],
       [504, 130, 306, 136, 440],
       [423, 383, 127,  61, 221]])

In [120]:
np.maximum(array8, array9)

array([[412, 293, 109, 452, 405],
       [432, 385, 508, 479, 530],
       [504, 390, 306, 508, 440],
       [448, 530, 127, 147, 221]])

In [126]:
np.unique(array8)

array([ 47,  72,  94, 109, 132, 147, 176, 219, 363, 385, 390, 412, 437,
       448, 479, 508, 530])

In [129]:
array10 = np.union1d(array8, array9)

In [130]:
type(array10)

numpy.ndarray

In [132]:
type(list(array10))

list

# Practicando Pandas

In [141]:
data = {'ciudad': ['Madrid', 'Barcelona', 'Bilbao', 'Valencia', 'Sevilla', 'Teruel', 'Soria'],
        'pop': [5.2, 4.8, 2.1, 1.8, 2, 0.8, 0.2],
        'bolsa': [True, True, True, True, False, False, False]}

In [149]:
data['ciudad']

['Madrid', 'Barcelona', 'Bilbao', 'Valencia', 'Sevilla', 'Teruel', 'Soria']

In [154]:
data['pop']

list

In [178]:
data.values()

dict_values([['Madrid', 'Barcelona', 'Bilbao', 'Valencia', 'Sevilla', 'Teruel', 'Soria'], [5.2, 4.8, 2.1, 1.8, 2, 0.8, 0.2], [True, True, True, True, False, False, False]])

In [179]:
data.keys()

dict_keys(['ciudad', 'pop', 'bolsa'])

In [164]:
df = pd.DataFrame(data, index = np.arange(1, 8))
df

ciudad  pop  bolsa
1     Madrid  5.2   True
2  Barcelona  4.8   True
3     Bilbao  2.1   True
4   Valencia  1.8   True
5    Sevilla  2.0  False
6     Teruel  0.8  False
7      Soria  0.2  False

In [172]:
df['pop'] #Muestra filas de sólo una columna

1    5.2
2    4.8
3    2.1
4    1.8
5    2.0
6    0.8
7    0.2
Name: pop, dtype: float64

In [174]:
df[2:] #Muestra filas

ciudad  pop  bolsa
3    Bilbao  2.1   True
4  Valencia  1.8   True
5   Sevilla  2.0  False
6    Teruel  0.8  False
7     Soria  0.2  False

In [167]:
df.head(1)

ciudad  pop  bolsa
1  Madrid  5.2   True

In [168]:
df.tail(1)

ciudad  pop  bolsa
7  Soria  0.2  False

In [175]:
df.index

Int64Index([1, 2, 3, 4, 5, 6, 7], dtype='int64')

In [176]:
df.columns

Index(['ciudad', 'pop', 'bolsa'], dtype='object')

In [177]:
df.values

array([['Madrid', 5.2, True],
       ['Barcelona', 4.8, True],
       ['Bilbao', 2.1, True],
       ['Valencia', 1.8, True],
       ['Sevilla', 2.0, False],
       ['Teruel', 0.8, False],
       ['Soria', 0.2, False]], dtype=object)

In [182]:
df.count()

ciudad    7
pop       7
bolsa     7
dtype: int64

In [187]:
df.sum(df)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [193]:
df.columns = ['city', 'pop','bolsa'] #Cambiar nombre a columnas
df

city  pop  bolsa
1     Madrid  5.2   True
2  Barcelona  4.8   True
3     Bilbao  2.1   True
4   Valencia  1.8   True
5    Sevilla  2.0  False
6     Teruel  0.8  False
7      Soria  0.2  False

In [194]:
df.city

1       Madrid
2    Barcelona
3       Bilbao
4     Valencia
5      Sevilla
6       Teruel
7        Soria
Name: city, dtype: object

In [195]:
df['city']

1       Madrid
2    Barcelona
3       Bilbao
4     Valencia
5      Sevilla
6       Teruel
7        Soria
Name: city, dtype: object

In [196]:
df['bolsa']

1     True
2     True
3     True
4     True
5    False
6    False
7    False
Name: bolsa, dtype: bool

In [198]:
df.loc[2]

city     Barcelona
pop            4.8
bolsa         True
Name: 2, dtype: object

In [199]:
df.loc[df.index>3]

city  pop  bolsa
4  Valencia  1.8   True
5   Sevilla  2.0  False
6    Teruel  0.8  False
7     Soria  0.2  False

In [204]:
df.loc[df.index>2, 'nueva'] = 5
df

city  pop  bolsa  nueva
1     Madrid  5.2   True    NaN
2  Barcelona  4.8   True    NaN
3     Bilbao  2.1   True    5.0
4   Valencia  1.8   True    5.0
5    Sevilla  2.0  False    5.0
6     Teruel  0.8  False    5.0
7      Soria  0.2  False    5.0

In [206]:
df_2 = df.drop('bolsa', axis=1)
df_2

city  pop  nueva
1     Madrid  5.2    NaN
2  Barcelona  4.8    NaN
3     Bilbao  2.1    5.0
4   Valencia  1.8    5.0
5    Sevilla  2.0    5.0
6     Teruel  0.8    5.0
7      Soria  0.2    5.0