# Practicando Numpy

## Creando arrays de número aleatorios

In [8]:
import numpy as np

In [4]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
array2 = np.arange(1,100,10)
array2

array([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [21]:
array3 = np.random.random(5)
print(array3)
print(array3.shape)
print(array3.size)

[0.56804456 0.92559664 0.07103606 0.0871293  0.0202184 ]
(5,)
5


5

(5,)

In [22]:
array4 = np.random.randint(100, 1000, (3, 4)) 
print(array4)
print(array4.shape)
print(array4.size)

[[855 809 947 531]
 [548 950 199 277]
 [855 897 759 247]]
(3, 4)
12


In [26]:
np.random.seed(0) # Ponemos la semilla a 0 (puede ser cualquier número)
array5 = np.random.rand()
array5

0.5488135039273248

## Selección de valores, indexación

In [57]:
array5 = np.random.randint(40, 540, (5, 6)) 
array5

array([[ 57, 524, 314, 191, 389, 409],
       [ 42, 406,  76, 206, 169,  71],
       [230, 232, 406, 220, 293, 328],
       [185,  62, 460, 149, 443, 420],
       [ 97, 126, 144, 121, 495,  82]])

In [23]:
array5[1:3] #Coge las filas desde 1 al 3

array([[255, 465, 342, 304, 508,  50],
       [125,  79, 360, 244, 377, 113]])

In [24]:
array5[1]

array([255, 465, 342, 304, 508,  50])

In [25]:
array5[1,3] #Coge el dato concreto

304

In [26]:
array5[0:2,5]

array([116,  50])

In [45]:
array5[array5 >300]

array([448, 426, 522, 401, 335, 509, 483, 453, 351, 439, 437, 381, 385,
       348])

In [59]:
array5.sort() #Ordena
array5

array([[ 57, 191, 314, 389, 409, 524],
       [ 42,  71,  76, 169, 206, 406],
       [220, 230, 232, 293, 328, 406],
       [ 62, 149, 185, 420, 443, 460],
       [ 82,  97, 121, 126, 144, 495]])

In [69]:
array5.any(axis=0)

array([ True,  True,  True,  True,  True,  True])

In [102]:
array6 = np.random.random(5)
array6.round() == 1

array([False,  True,  True, False,  True])

In [101]:
array6

array([0.38027906, 0.93281949, 0.67092635, 0.86711585, 0.75920124])